import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "./Navigation/page";
import Herosection from "./Herosection/page";
import Banner from "./Banner/page";
import Achievement from "./Achievement/page";
import Achievements from "./achievements/page";
import Services from "./Services/page";
import Courses from "./Courses/page";
import OurTeam from "./OurTeam/page";
import Testimonial from "./Testimonial/page";
import Footer from "./Footer/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      
        {children}
       
      </body>
    </html>
  );
}
